### ISSUE TITLE
sbt compile fails to build project

### ISSUE THREAD

**Issue by xylo** [TakehideSoh/Scarab#7] opened 2016-06-09 08:26 UTC
```
$ sbt compile
[warn] The global sbt directory is now versioned and is located at /home/stefan/.sbt/0.13.
[warn]   You are seeing this warning because there is global configuration in /home/stefan/.sbt but not in /home/stefan/.sbt/0.13.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[info] Loading project definition from /home/stefan/software/Scarab/project
[warn] The global sbt directory is now versioned and is located at /home/stefan/.sbt/0.13.
[warn]   You are seeing this warning because there is global configuration in /home/stefan/.sbt but not in /home/stefan/.sbt/0.13.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[info] Updating {file:/home/stefan/software/Scarab/project/}scarab-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
Missing bintray credentials /home/stefan/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /home/stefan/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to Scarab (in build file:/home/stefan/software/Scarab/)
[warn] The global sbt directory is now versioned and is located at /home/stefan/.sbt/0.13.
[warn]   You are seeing this warning because there is global configuration in /home/stefan/.sbt but not in /home/stefan/.sbt/0.13.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[warn] The global sbt directory is now versioned and is located at /home/stefan/.sbt/0.13.
[warn]   You are seeing this warning because there is global configuration in /home/stefan/.sbt but not in /home/stefan/.sbt/0.13.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[warn] Credentials file /home/stefan/.bintray/.credentials does not exist
[info] Updating {file:/home/stefan/software/Scarab/}sat4jCore...
[warn] Credentials file /home/stefan/.bintray/.credentials does not exist
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Updating {file:/home/stefan/software/Scarab/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 241 Java sources to /home/stefan/software/Scarab/org.sat4j.core/target/classes...
[info] /home/stefan/software/Scarab/org.sat4j.core/src/main/java/org/sat4j/tools/SolverDecorator.java: Some input files use or override a deprecated API.
[info] /home/stefan/software/Scarab/org.sat4j.core/src/main/java/org/sat4j/tools/SolverDecorator.java: Recompile with -Xlint:deprecation for details.
[info] /home/stefan/software/Scarab/org.sat4j.core/src/main/java/org/sat4j/AbstractLauncher.java: Some input files use unchecked or unsafe operations.
[info] /home/stefan/software/Scarab/org.sat4j.core/src/main/java/org/sat4j/AbstractLauncher.java: Recompile with -Xlint:unchecked for details.
[info] Compiling 15 Scala sources to /home/stefan/software/Scarab/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.6. Compiling...
[info]   Compilation completed in 14.059 s
[error] /home/stefan/software/Scarab/src/main/scala/jp/kobe_u/scarab/Sat4j.scala:134: not found: type BlockedBC
[error]     sat4j.addConstr(new BlockedBC(minisat, minisat.dimacs2internal(new VecInt((block +: lits).toArray)), degree))
[error]                         ^
[error] /home/stefan/software/Scarab/src/main/scala/jp/kobe_u/scarab/Sat4jPB.scala:3: object pb is not a member of package org.sat4j
[error] import org.sat4j.pb.SolverFactory
[error]                  ^
[error] /home/stefan/software/Scarab/src/main/scala/jp/kobe_u/scarab/Sat4jPB.scala:4: object pb is not a member of package org.sat4j
[error] import org.sat4j.pb._
[error]                  ^
[error] /home/stefan/software/Scarab/src/main/scala/jp/kobe_u/scarab/Sat4jPB.scala:9: not found: type IPBSolver
[error]   val sat4jpb: IPBSolver = SolverFactory.instance.createSolverByName("Default")
[error]                ^
[error] /home/stefan/software/Scarab/src/main/scala/jp/kobe_u/scarab/Sat4jPB.scala:9: not found: value SolverFactory
[error]   val sat4jpb: IPBSolver = SolverFactory.instance.createSolverByName("Default")
[error]                            ^
[error] 5 errors found
[error] (root/compile:compileIncremental) Compilation failed
[error] Total time: 24 s, completed 09.06.2016 10:24:10

```

**Comment by TakehideSoh** [comment] 2016-07-01 05:44
Thank you for the report. The issue is fixed by the updated build.sbt.

**Closed as completed by TakehideSoh** 2016-07-01 05:44 UTC

**Comment by TakehideSoh** [comment] 2016-07-01 06:06
I further modify build.sbt so that it can assemble Scarab with all dependencies.
